style/.rubocop.yml
It's a rare case, but some Ruby scripts may appear in /tmp.  Typically they are autogenerated by some gems, for example Aruba may create pretty arbitrary files for test purposes.  They are volatile, and definitely do not belong to repository.  Checking them in CI seems pointless, and they may be a source of noise when running Rubocop locally.
=> Exclude temporary files from Rubocop checks

style/.rubocop.yml
Many open source gems define several gemfiles for CI tests against different dependency combinations.  For example, Ribose's [attr_masker](https://github.com/riboseinc/attr_masker/tree/master/gemfiles). These files should be checked as well.
=> Check style for custom gemfiles

style/.rubocop.ribose.yml
A tiny update to Thoughtbot's style guide (cop name update), see: https://github.com/thoughtbot/guides/pull/506
=> Upgrade linked Thoughtbot's guide (fix warning)

style/.rubocop.ribose.yml, style/.rubocop.tb.yml, style/.rubocop.yml
Continuation of #3.
Looks like my previous observations were wrong, and Hound does not support style guide inheritance from remote URLs. Maybe I've looked at some stale Hound comment (I was changing guide several times), or simply overlooked something, I don't know. The fact is that we can't inherit style guides from remote URLs. Hound maintainers have their reasons for that: https://github.com/houndci/hound/issues/996.
The simplest solution is to keep the style guides locally. Only the Thoughtbot's guide is expected to be updated frequently, hence there shouldn't be much hassle. However, we may try out [Hound's style guides for organizations](https://robots.thoughtbot.com/hound-introduces-style-guides-for-organisations) to make it all easier.
FYI @ribose-jeffreylau @ronaldtse @abunashir.
=> Do not use remote style guides

style/.rubocop.tb.yml
Upgarde Thoughtbot's style guide for Rubocop 0.53-0.54, see: https://github.com/thoughtbot/guides/pull/510
Hound runs 0.54 at the moment.
Oh, and it fixes #9.
=> Upgrade embedded Thoughtbot's guide

ci/rubocop.yml, src/rubocop/rubocop.ribose.yml
Rely on Rubocop's defaults, which are far more comprehensive, as of Rubocop v0.54 currently run by Hound CI.
See: https://github.com/rubocop-hq/rubocop/blob/v0.54.0/config/default.yml
Fixes #12. Obsoletes #18.
=> Remove our Rubocop includes

.hound.yml, ci/rubocop.yml, src/rubocop/rubocop.tb.yml
- Bump Rubocop version to 0.75.0 in Hound CI config
- Upgrade embedded Thoughtbot's guide
- Rebuild style guide from sources
Last time we bumped Rubocop version was exactly one year ago, and it's time to do it again.  Rubocop 0.75.0 is currently the most recent version supported by Hound CI.
Thoughtbot's style guide comes from revision: https://github.com/thoughtbot/guides/blob/a5f5fd36dc/style/ruby/.rubocop.yml. Newer commits address changes which has been introduced to Rubocop after version 0.75, and are not backwards compatible.
=> Switch to Rubocop 0.75.0

ci/rubocop.yml
https://github.com/rubocop/rubocop/releases/tag/v1.5.0
- rubocop/rubocop#9098: Update Metrics/BlockLength and Metrics/MethodLength to use IgnoredMethods instead of ExcludedMethods in configuration. The previous key is retained for backwards compatibility.
https://github.com/rubocop/rubocop/releases/tag/v0.78.0
- rubocop/rubocop#7542: (Breaking) Move LineLength cop from Metrics department to Layout department.
@CAMOBAP don't forget to merge https://github.com/CAMOBAP/oss-guides/pull/1 once this one will be approved
=> Feature/update rubocop 1.5.0

.hound.yml
The style book has been updated to be compatible with Rubocop 1.5.2 (#31), but Hound CI configuration hasn't been changed accordingly.
=> Switch to Rubocop 1.5.2 in Hound CI

src/rubocop/rubocop.ribose.yml
There were some recent changes made in the compiled style book (`ci/*`) rather than in source files (`src/*`).  In this pull request they are moved to a proper place. Otherwise they would be overwritten at next recompile.
=> Preserve recent style book changes for being overwritten

ci/rubocop.yml, src/rubocop/rubocop.tb.yml
Fixes #32. Updated Thoughtbot's style guide comes from revision: https://github.com/thoughtbot/guides/blob/20b0d3b86040964e1ef1450b62e56b1aa62a6e76/ruby/.rubocop.yml.
=> Update underlying Thoughtbot's style guide

src/rubocop/rubocop.ribose.yml
These checks are completely irrelevant for most of our projects as they do not use Rails.
=> Disable all cops from Rails department

.github/workflows/integrity_test.yml
Use GitHub Actions to ensure that no one forgot about recompiling the style book. Should prevent from issues like #44/#45 in future.
=> Test style book integrity in GHA

ci/rubocop.yml, src/rubocop/rubocop.ribose.yml
About two weeks ago I've opened discussion about following changes:
- Disable Style/CollectionMethods (fixes #35)
- Enable Style/ArgumentsForwarding (fixes #41)
- Reconfigure Style/TrailingCommaInArguments to enforce trailing commas in multiline argument lists (fixes #37)
These changes are non-controversial I think, and I'm going to merge them in a few days unless someone opposes.
=> Small changes to Ruby style book

src/rubocop/rubocop.ribose.yml
I'm not sure about the 'level' where we should define this, maybe https://github.com/metanorma/metanorma-build-scripts/blob/main/cimas-config/gh-actions/master/.rubocop.yml is better
=> Add Gemspec/RequireMFA/Enabled:false

ci/rubocop.yml, src/rubocop/rubocop.ribose.yml
=> Bump TargetRubyVersion in rubocop configs to 2.5 (#54)

.hound.yml, Rakefile, ci/rubocop.rails.yml, ci/rubocop.yml, src/rubocop/rubocop.ribose.yml
Fixes #67 , but needs further clarification on desired dot position style.
=> Fix merge behaviours of configs

ci/rubocop.rails.yml, ci/rubocop.yml, src/rubocop/rubocop.ribose.yml
=> rubocop: Enable Style/CollectionCompact for consistent nil checks

README.adoc
=> doc: Update README to reflect recent changes

ci/rubocop.rails.yml, ci/rubocop.yml, src/rubocop/rubocop.ribose.yml
Fixes #42 by enabling all suggested checks.
=> Enable more rubocop checks
